######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 15 19:49:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fm.h mainform.h qclickablelabel.h
FORMS += mainform.ui
SOURCES += fm.cpp main.cpp mainform.cpp qclickablelabel.cpp
RESOURCES += img.qrc
QT += network
LIBS += -lqjson
