######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 9 22:52:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fm.h mainform.h
FORMS += mainform.ui
SOURCES += fm.cpp main.cpp mainform.cpp
RESOURCES += img.qrc
QT += network
LIBS += -lqjson
